version: 2.1

orbs:
    node: circleci/node@7.2.1

jobs:
    build-and-test:
        docker: # image to run on
            - image: cimg/node:18.20.5
        resource_class: xlarge # how much CPU/RAM
        parallelism: 15 # nodes to split test suite over
        steps:
            - checkout
            - node/install-packages:
                pkg-manager: yarn
            - run: mkdir ~/junit
            - run: # split test suite over the parallel nodes
                name: Test application
                command: |
                    TEST=$(circleci tests glob "src/__tests__/*.js" | circleci tests split --split-by=timings)
                    yarn test $TEST
            - run:
                command: cp junit.xml ~/junit/
                when: always
            - store_test_results:
                path: ~/junit
            - store_artifacts:
                path: ~/junit
workflows:
    build-and-test:
      jobs:
        - build-and-test
